DROP SCHEMA IF EXISTS boardgameDev;
CREATE DATABASE IF NOT EXISTS boardgameDev;
USE boardgameDev;

CREATE TABLE IF NOT EXISTS RESERVATION_PRICE (
    RESERVATION_PRICE_NO INT NOT NULL,
    RESERVATION_PRICE INT UNSIGNED,
    TIME_START DATE,
    TIME_END DATE,
    PRIMARY KEY (RESERVATION_PRICE_NO)
);

CREATE TABLE IF NOT EXISTS OPENNING_TIME (
    OPENTIME_NO INT,
    WEEK TINYINT,
    OPENTIME_START TIME,
    OPENTIME_END TIME,
    PRIMARY KEY (OPENTIME_NO)
);

CREATE TABLE IF NOT EXISTS EMPLOYEE (
    EMPLOYEE_NO INT NOT NULL AUTO_INCREMENT,
    EMPLOYEE_NAME VARCHAR(10) NOT NULL,
    EMPLOYEE_PHONE VARCHAR(10),
    EMPLOYEE_ADDRESS VARCHAR(100),
    EMPLOYEE_EMAIL VARCHAR(30) NOT NULL,
    EMPLOYEE_PASSWORD VARCHAR(40) NOT NULL,
    ROLE_NO INT,
    EMPLOYEE_STATUS TINYINT,
    PRIMARY KEY (EMPLOYEE_NO)
);

CREATE TABLE IF NOT EXISTS ROLE (
    ROLE_NO INT NOT NULL AUTO_INCREMENT,
    ROLE_NAME VARCHAR(15) NOT NULL,
    PRIMARY KEY (ROLE_NO)
);

CREATE TABLE IF NOT EXISTS ROLE_PERMISSIONS (
    ROLE_PERMS_NO INT NOT NULL AUTO_INCREMENT,
    ROLE_NO INT NOT NULL,
    PERMS_NO INT NOT NULL, -- not sure yet
    PRIMARY KEY (ROLE_PERMS_NO)
);

-- INSERT

INSERT INTO RESERVATION_PRICE (RESERVATION_PRICE_NO, RESERVATION_PRICE, TIME_START, TIME_END)
VALUES
    (1, 100, '2020-01-01', '2023-03-01'),
    (2, 200, '2023-03-01', '2050-12-31');


INSERT INTO OPENNING_TIME (OPENTIME_NO, WEEK, OPENTIME_START, OPENTIME_END)
VALUES
    (1, 1, '11:00:00', '21:00:00'),
    (2, 2, '11:00:00', '21:00:00'),
    (3, 3, '11:00:00', '21:00:00'),
    (4, 4, '11:00:00', '21:00:00'),
    (5, 5, '11:00:00', '21:00:00'),
    (6, 6, '09:00:00', '23:00:00'),
    (7, 7, '09:00:00', '23:00:00');

INSERT INTO EMPLOYEE (EMPLOYEE_NAME, EMPLOYEE_PHONE, EMPLOYEE_ADDRESS, EMPLOYEE_EMAIL, EMPLOYEE_PASSWORD, ROLE_NO, EMPLOYEE_STATUS)
VALUES
('李四', '0987654321', '台灣台北市大安區', 'lisi@example.com', 'mypassword', 1, 1),
('王五', '0912345678', '台灣台中市南區', 'wangwu@example.com', 'mypassword', 2, 1),
('陳六', '0922333444', '台灣高雄市三民區', 'chenliu@example.com', 'mypassword', 2, 0),
('林七', '0933123456', '台灣新北市板橋區', 'linqi@example.com', 'mypassword', 3, 1),
('張八', '0977888999', '台灣桃園市龜山區', 'zhangba@example.com', 'mypassword', 3, 0);

INSERT INTO ROLE (ROLE_NAME)
VALUES ('Admin'), ('Manager'), ('Others');

INSERT INTO ROLE_PERMISSIONS (ROLE_NO, PERMS_NO)
VALUES (1, 1), (2, 2);

-- CIBSTRAINT FK

ALTER TABLE EMPLOYEE
ADD CONSTRAINT FK_ROLE_NO
FOREIGN KEY (ROLE_NO) REFERENCES ROLE(ROLE_NO);

ALTER TABLE ROLE_PERMISSIONS
ADD CONSTRAINT fk_role_perms_role_no
    FOREIGN KEY (ROLE_NO)
    REFERENCES ROLE(ROLE_NO);

-- ALTER TABLE ROLE_PERMISSIONS
-- ADD CONSTRAINT fk_role_perms_perms_no
--     FOREIGN KEY (PERMS_NO)
--     REFERENCES PERMISSIONS(PERMS_NO);